name: SparkAutoML
channels:
  - defaults
  - conda-forge
dependencies:
  - appdirs=1.4.4
  - attrs=21.2.0
  - black=19.10
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - click=8.0.3
  - mypy_extensions=0.4.3
  - openssl=1.1.1
  - pathspec=0.7.0
  - pip=21.2.4
  - python=3.9.7
  - pytest=6.2.4
  - regex=2021.8.3
  - setuptools=58.0.4
  - sqlite=3.36.0
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.0
  - pip:
    - numpy==1.21.4
    - pandas==1.3.4
    - pyspark>=3.2.1
    - PyArrow >= 1.0.0
    - pytest >= 7.1.1
    
